---
- hosts: all
  gather_facts: true
  become: true
  tasks: 
  - name: Create a simple file
    file: 
      path: /opt/ansible.txt
      state: touch 
      
  - name: To check the file existance
    shell: if [[ -d  "/opt" ]]; then echo "true";  fi
    register: file_exists
